#!/bin/bash
#PBS -N trim_align_markdup
#PBS -q default
#PBS -l select=1:ncpus=16:mem=64gb
#PBS -l walltime=08:00:00
#PBS -J 1-9
#PBS -j oe
#PBS -W group_list=x-ccast-prj-hulke

set -euo pipefail

################
# Check if arguments were provided and exist

REQUIRED_ARGS=("SAMPLE_LIST" "FQ_DIR" "OUT_DIR")

check_argument() {
local arg_name=$1
if [ -z $arg_name ]; then
	echo "Error: Required arguments are missing"
	echo "Usage: qsub -v SAMPLE_LIST=/path/to/list.txt,FQ_DIR=/path/to/fastqs,OUT_DIR=/where/want/bams script.pbs"
	exit 1
fi
}

echo "Checking required arguments..."
for arg in ${REQUIRED_ARGS[@]}; do
	check_argument $arg
done

if [ ! -f $SAMPLE_LIST ]; then
	echo "Error: $SAMPLE_LIST not found."
	exit 1
fi

if [ ! -d $FQ_DIR ]; then
	echo "Error: $FQ_DIR not found."
	exit 1
fi

################
# set variables

sample_list=$SAMPLE_LIST
sample=$(sed -n "${PBS_ARRAY_INDEX}p" $sample_list)
fq_dir=$FQ_DIR
out_dir=$OUT_DIR
ref=/mmfs1/projects/brent.hulke/sunflower_reference_genomes/HA412HOv2_w_CPMT/Ha412HOv2_w_CPMT.fa
software=/mmfs1/projects/brent.hulke/Software

################
# make necessary output directories and load software
start=$(date +%s)
mkdir -p $out_dir/fastp_out
mkdir -p $out_dir/markdup_out
mkdir -p $out_dir/flagstat_out

module load samtools/1.20

################
# MAIN
# trim (fastp), align (bwa-mem2) mark duplicates (samtools markdup),
# index (samtools), get metrics (mosdepth, samtools flagstat)

$software/fastp \
	-i $fq_dir/${sample}_*1.f*q.gz \
	-I $fq_dir/${sample}_*2.f*q.gz \
	-h $out_dir/fastp_out/$sample.html \
	-j $out_dir/fastp_out/$sample.json \
	-w 16 \
	--stdout \
| $software/bwa-mem2/bwa-mem2 \
	mem -p -R "@RG\tID:$sample\tSM:$sample" -t 16 $ref - \
	| samtools collate -@ 16 -O - \
	| samtools fixmate -@ 16 -m - - \
	| samtools sort -@ 16 - \
	| samtools markdup -@ 16 \
		-f $out_dir/markdup_out/$sample.stats \
		- $out_dir/$sample.bam

samtools index $out_dir/$sample.bam
$software/mosdepth_d4 -t 16 --d4 $out_dir/mosdepth_out/$sample $out_dir/$sample.bam
samtools flagstat -@ 16 $out_dir/$sample.bam > $out_dir/flagstat_out/$sample.flagstat

################

end=$(date +%s)
time_elapsed=$((end-start))
echo "Total time: $time_elapsed seconds"
