#!/bin/bash
#PBS -N HaplotypeCaller
#PBS -q default
#PBS -l select=1:ncpus=17:mem=68gb
#PBS -l walltime=24:00:00
#PBS -J 10-13
#PBS -j oe
#PBS -W group_list=x-ccast-prj-hulke

set -euo pipefail

################
# Check if arguments were provided and exist

REQUIRED_ARGS=("SAMPLE_LIST" "BAM_DIR" "OUT_DIR")

check_argument() {
local arg_name=$1
if [ -z $arg_name ]; then
	echo "Error: Required arguments are missing"
	echo "Usage: qsub -v SAMPLE_LIST=/path/to/list.txt,BAM_DIR=/path/to/bams,OUT_DIR=/where/want/gvcfs script.pbs"
	exit 1
fi
}

echo "Checking required arguments..."
for arg in ${REQUIRED_ARGS[@]}; do
	check_argument $arg
done

if [ ! -f $SAMPLE_LIST ]; then
	echo "Error: $SAMPLE_LIST not found."
	exit 1
fi

if [ ! -d $BAM_DIR ]; then
	echo "Error: $BAM_DIR not found."
	exit 1
fi

################
# set variables
TMPDIR=$SCRATCH
genome_dir=/mmfs1/projects/brent.hulke/sunflower_reference_genomes/HA412HOv2_w_CPMT
ref=$genome_dir/Ha412HOv2_w_CPMT.fa
repeats=$genome_dir/helianthusannuus.filteredRepeats.17_chromosomes.bed
chromosomes=$genome_dir/sunflower_orcc/17_chromosomes_Ha412HOv2.list
sample_list=$SAMPLE_LIST
sample=$(sed -n "${PBS_ARRAY_INDEX}p" $sample_list)
bam_dir=$BAM_DIR
out_dir=$OUT_DIR

################
# make necessary output directories and load software
start=$(date +%s)
mkdir -p $out_dir

module load gatk; module load parallel

################
# MAIN
# function to run HC on an individual chromosome
call_variants_per_chrom() {
local chrom=$1
mkdir -p $out_dir/$chrom
gatk HaplotypeCaller \
	-R $ref \
	-I $bam_dir/$sample.bam \
	--intervals $chrom \
	--exclude-intervals $repeats \
	--emit-ref-confidence GVCF \
	--heterozygosity 0.01 \
	--heterozygosity-stdev 0.1 \
	--native-pair-hmm-threads 1 \
	-O $out_dir/$chrom/$sample.$chrom.g.vcf.gz
}

# use gnu parallel to run HC for each chromosome in parallel
export -f call_variants_per_chrom
export TMPDIR ref sample bam_dir out_dir repeats
cat $chromosomes | parallel -j -17 call_variants_per_chrom

end=$(date +%s)
time_elapsed=$((end-start))
echo "Total time: $time_elapsed seconds"
