#!/bin/bash
#PBS -N GenomicsDBImport_GenotypeGVCFs
#PBS -q condo05
#PBS -l select=1:ncpus=16:mem=125gb
#PBS -l walltime=168:00:00
#PBS -J 1-17
#PBS -j oe
#PBS -W group_list=x-ccast-prj-hulke

set -euo pipefail

################
# REQUIRED_ARGS: "SAMPLE_LIST" "GVCF_DIR" "COHORT" "OUT_DIR"

# Usage: qsub -v SAMPLE_LIST=/path/to/list.txt,GVCF_DIR=/path/to/gvcfs,COHORT=cohort_name,OUT_DIR=/where/want/vcfs 03_GenomicsDBImport_GenotypeGVCFs.pbs

################
# set variables
genome_dir=/mmfs1/projects/brent.hulke/sunflower_reference_genomes/HA412HOv2_w_CPMT
ref=$genome_dir/Ha412HOv2_w_CPMT.fa
chromosomes=$genome_dir/17_chromosomes_Ha412HOv2.list
chrom=$(sed -n "${PBS_ARRAY_INDEX}p" $chromosomes)
sample_list=$SAMPLE_LIST
gvcf_dir=$GVCF_DIR
cohort=$COHORT
out_dir=$OUT_DIR

################
# MAIN
# make sample name map required by GenomicsDBImport: matches sample names to gvcf file paths
start=$(date +%s)
cd $SCRATCH
rm -f $SCRATCH/$cohort.$chrom.sample_map

sort $sample_list | while read -r sample; do
    file=$(ls $gvcf_dir/$chrom/${sample}*.g.vcf.gz 2>/dev/null)
    if [[ -n "$file" ]]; then
        echo -e "$sample\t$file" >> $SCRATCH/$cohort.$chrom.sample_map
    else
        echo "Warning: No matching file found for sample $sample" >&2
    fi
done

# make seperate db for each of 17 chroms (uses job array as specified in header)
module load gatk
gatk --java-options "-Xmx125g -XX:ParallelGCThreads=16" GenomicsDBImport \
	--genomicsdb-workspace-path $SCRATCH/$cohort.$chrom.gdb \
	--sample-name-map $SCRATCH/$cohort.$chrom.sample_map \
	-L $chrom \
	--tmp-dir $SCRATCH \
	--reader-threads 16 \
	--overwrite-existing-genomicsdb-workspace

# make cohort vcf for each chrom
gatk --java-options "-Xmx125g -XX:ParallelGCThreads=16" GenotypeGVCFs \
	-R $ref \
	-V gendb://$SCRATCH/$cohort.$chrom.gdb \
	-L $chrom \
	--heterozygosity 0.01 \
	--heterozygosity-stdev 0.1 \
	-O $out_dir/$cohort.$chrom.vcf.gz

end=$(date +%s)
time_elapsed=$((end-start))
echo "Total time: $time_elapsed seconds"
